AWSTemplateFormatVersion: '2010-09-09'

Resources:
  InstanceAppDb:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0e86e20dae9224db8
      InstanceType: t2.micro
      KeyName: dyagent
      SubnetId: !ImportValue PublicSubnetId
      SecurityGroupIds: 
        - !ImportValue InstanceSecurityGroupId
      Tags:
        - Key: Name
          Value: appDb

  InstancePrometheusGrafana:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0e86e20dae9224db8
      InstanceType: t3.medium
      KeyName: dyagent
      SubnetId: !ImportValue PublicSubnetId
      SecurityGroupIds: 
        - !ImportValue InstanceSecurityGroupId
      Tags:
        - Key: Name
          Value: prometheusGrafana

Outputs:
  InstanceAppDbPublicIP:
    Description: Public IP address of the App DB instance
    Value: !GetAtt InstanceAppDb.PublicIp
    Export:
      Name: AppDbInstancePublicIP

  InstancePrometheusGrafanaPublicIP:
    Description: Public IP address of the Prometheus and Grafana instance
    Value: !GetAtt InstancePrometheusGrafana.PublicIp
    Export:
      Name: PrometheusGrafanaInstancePublicIP
